### ISSUE TITLE
RoboFont script to set up the editor prefs with the nice mark colors (with semantic names)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontelemetry#13]
I think it would be good to have a script that turns the color definitions in a project into the local user apps's prefs 

https://robofont.com/documentation/how-tos/working-with-mark-colors/?highlight=mark

**Comment by chrissimpkins** [comment]
I don't have a copy of RoboFont which limits my ability to work on this...

It looks like the mark definitions are saved in system-wide RoboFont specific settings and apply to all font projects developed on a user's platform.  I would need to explore those settings files and see if we can pull the `color:name` data out of them.

<img width="752" alt="d9p9j-image" src="https://user-images.githubusercontent.com/4249591/52362844-78bc6780-2a0f-11e9-8313-a9fff69d622c.png">

Open to developing this if someone who is using RoboFont would be willing to help me look into whether those settings files are text vs binary, the path that they are on, and what format they use to store the color data.  @jeremiehornus do you happen to know?

**Comment by BlackFoundry** [comment]
RoboFont can be [downloaded here](http://static.typemytype.com/robofont/RoboFont.dmg)

Application's custom colors can be stored like that:
# Mark colors
"markColors": [
      [[1, 0, 0, 1], "red"],
      [[1, 1, 0, 1], "yellow"],
      [[0, 0, 1, 1], "blue"],
      [[1, 1, 1, 1], "white"],
      [[0, 1, 0, 1], "green"],
      [[1, 0.1741, 1, 1], "test"],
      [[0.8041, 0.9982, 0, 1], "Rename me"]
   ],

but this is specific to each user, each copy of RoboFont can be customized with its own colors

**Comment by chrissimpkins** [comment]
Thanks Jeremie! I really appreciate the input.  

What is the path for those RoboFont settings files?

**Comment by BlackFoundry** [comment]
Within RoboFont you can use this kind of scripting:
``` python
import mojo.UI as mui

def colorTagExists(tag, prefs):
    colors = list(prefs['markColors'])
    for color in colors:
        code = color[0]
        name = color[1]
        if name == tag:
            return(True)
    return(False)

def appendMarkColor(code, tag): 
    prefs = mui.exportPreferences()
    if colorTagExists(tag, prefs):
        return
    colors = list(prefs['markColors'])
    colors.append((code, tag))
    prefs['markColors'] = colors
    mui.importPreferences(prefs)

# Usage
mycode = (.5, .5, .5, 1)
mytag = 'gray'
appendMarkColor(mycode, mytag)
```

Otherwise, the preference file is in Library/Preferences/com.typemytype.robofont3.plist

**Comment by chrissimpkins** [comment]
Thank you!  The source appears to all be included there.  The only missing pieces would be to create a `color`:`tag` spec and export the `prefs['markColors']` data as a toml formatted file.  

The former requires a bit of discussion.  The latter is trivial. 

We can start from the following approach and decide if any modification is necessary?

```
Backlog: (.5, 0, 0, 1) # dark red
To Do (1, .3, 0, 1) # orange
In Progress: (.6, 0, .8, 1) # purple
Proofing: (.8, 1, 0, 1) # lime
Done: (1, 1, 1, 1) # white
```

I'd recommend that we add a "Done` category to that classification system.   Perhaps "Done" = no color = white or it could be green?

Edit: The above scheme would ~follow typical Kanban board columns...

**Comment by chrissimpkins** [comment]
`mojo` API docs:

`mui.UI.exportPreferences`: https://robofont.com/documentation/building-tools/api/mojo/mojo-ui/#mojo.UI.exportPreferences

`mui.UI.importPreferences`: https://robofont.com/documentation/building-tools/api/mojo/mojo-ui/#mojo.UI.importPreferences

**Comment by chrissimpkins** [comment]
Added a Python script that does not depend on Robofont API to address this.  The script does the following:

1. pulls public.markColor data from all UFO *.glif files
2. defines the unique set of rgba color values used in the project
3. formats these data in toml and dumps to standard out using spec used for settings files in this project.

The color names and color values can then be filled in with the appropriate values and it is gtg for use with the fontelemetry library mark color mapping to designer defined value labels.

Here is an example of the output:

```toml
[color.mark.ufo]
Color1 = [ "0.6,0,0.8,1", "Value1",]
Color2 = [ "0.5,0,0,1", "Value2",]
Color3 = [ "0.8,1,0,1", "Value3",]
white = [ "1.0,1.0,1.0,1", "ValueWhite",]
```

@jeremiehornus the data above were pulled from your project files.  White is defined by default in all projects for uncolored glyphs irrespective of whether uncolored glyphs were identified in the project.

Script pushed to tools directory of the repository in https://github.com/googlefonts/fontelemetry/commit/6e04ec6e0d29e69b5f038e1f7afce4c58e96ca21
