### ISSUE TITLE
Discussion on the name of this repo / project.

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontelemetry#16]
I got a bit puzzled by the usage of the term "font bakery" in the name of this repo.

I looked at the open issues trying to grasp be purpose of the project and it was not clear if that had any direct relation to https://github.com/googlefonts/fontbakery at all.

@davelab6 clarified that this is meant to be one component of the fontbakery-dashboard and I think that makes sense!

But I still think it would be good to consider changing its name to avoid confusion. For instance, the name `fontbakery-reporter` sounds vague to me and very similar to the idea of generating a report of font problems, while what @chrissimpkins is working on seems more focused on monitoring the progress of a font project.

**Comment by chrissimpkins** [comment]
The project will consist of a Python library, Python command line executable (possibly suite of executables depending upon needs that arise #12 ), and jupyter notebook templates that support report-style narratives with embedded executable code blocks that can be used to display font / type source / git VC + Github API / system executable-based metrics, analyses/comparisons/dataviz, & font renders in a dashboard telemetry style active document format that includes as much real-time data as possible at document execution time.  The initial recommended approach will likely be to add a jupyter notebook (probably a customized version of one that is hosted here as a template for d/l and use) to a typeface source repository and import the library for use in those `*.ipynb` source files. Anyone who wants to view the report can clone the typeface source repository (and thereafter pull recent commits) and execute the notebook to display as much real-time data on the project as is needed.  How this translates to the fontbakery db is TBD.  The connection to fontbakery in general is that QA reporting from the fontbakery tools would work very well through these documents IMO.  I intend to use fontbakery and other QA tools in a QA section of a report, and perhaps in a dedicated notebook that only deals with QA issues in a project.  Anything that you view in stdout from fontbakery or any other system-installed CLI tooling *should* be able to be executed at report build time for view in the document.

The primary goal is PM/QA reporting across the development of a typeface, but my goal is for the library to provide reasonably general purpose support for active document-style mixed narrative + executable code needs in the area of type software.  The design is still coming together but I think that most of the area-specific reporting needs will be implemented by customizing the jupyter notebook file source. The general purpose reporting needs will be built into the library.  That's the goal at least.  Let's see.  The project is only a few days old :)

Feedback on the project name/PyPI package name/approach outlined above is welcomed.  I'm open to change :)

**Comment by chrissimpkins** [comment]
From Font Bakery README:

> Font Bakery is a command-line tool for checking the quality of font projects

Based on that branding, I agree that this project seems out of scope in a way that Font Bakery Dashboard is not.  

@davelab6 do you have any thoughts since you recommended this name?  I'd like to settle this issue and refactor the paths + settings files if necessary.  The Travis/PyPI/RTD set up will be dependent on what we land on as the Github project name and PyPI package name.   If you don't feel compelled to keep this name, I can come up with a new one and let you know so that we can move the repository to address Felipe's concerns.

**Comment by chrissimpkins** [comment]
Emailed request to Dave for new package name and repository move with new name.  Thanks for weighing in here Felipe!

**Comment by felipesanches** [comment]
Thanks, @chrissimpkins!

**Comment by davelab6** [comment]
fontelemetry it is :)
